name: Test

on:
  push:
    branches:
      - master
      - next
      - beta
      - "greenkeeper/**"
      - 15.x
      - 16.x # TODO: can we use a pattern for these?

  pull_request:
    types: [opened, synchronize]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node_version: [8, 10, 12]

    steps:
      - uses: actions/checkout@master
      - name: Test with Node.js ${{ matrix.node_version }}
        uses: actions/setup-node@v1
        with:
          version: ${{ matrix.node_version }}
      - run: npm ci
      - run: npm run start-fixtures-server &
      - run: sleep 3 # give server some time to start
      - run: npm run test
